version: '3.4'

services:
  web:
    build: .
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/default?sslmode=disable
    volumes:
      - ./web:/go/src/app
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    links:
      - db
    command:
      - air
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/default?sslmode=disable
    volumes:
      - ./worker:/go/src

  db:
    image: postgres:alpine
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres